#!/usr/bin/env python3
"""Build app/assets/web/loudbook.js from the Chrome extension's shared code + web/bridge.js.
The extension (../Loudbook or $LOUDBOOK_EXT) is the single source of truth for how sites are read."""
import os, re, sys
here = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(here)
ext = os.environ.get('LOUDBOOK_EXT') or os.path.join(os.path.dirname(root), 'loudbook')
def read(p): return open(os.path.join(ext, p), encoding='utf-8').read()
def as_iife(src, name, exports):
    src = re.sub(r'^import .*$', '', src, flags=re.M)
    src = re.sub(r'^export (function|const|async function) ', r'\1 ', src, flags=re.M)
    return f"const {name} = (() => {{\n{src}\nreturn {{ {', '.join(exports)} }};\n}})();\n"
parts = [
    '// Loudbook for Android - generated by tools/bundle_web.py; edit the sources, not this file.\n',
    read('sites.js'),
    as_iife(read('lib/chunk.js'), 'LBChunk', ['chunkBlocks']),
    as_iife(read('lib/say.js'), 'LBSay', ['parseFixes', 'makeSayer', 'tidy']),
    open(os.path.join(root, 'web', 'bridge.js'), encoding='utf-8').read(),
]
# the page may inject this twice (reloads, back/forward); guard the top-level consts
body = '\n'.join(parts)
out = "if (!window.LB) {\n" + body + "\n}\n"
dest = os.path.join(root, 'app', 'assets', 'web', 'loudbook.js')
open(dest, 'w', encoding='utf-8').write(out)
print('wrote', dest, len(out), 'bytes')
